classdef instructionController
    properties
    end
    methods (Static)
        function displayInstruction(window, white, lang, instrIndex)
            if instrIndex == 0
                switch lang
                    case 'de'
                        instrStr = ['In der folgenden Aufgabe werden Sie auf jedem Bildschirm\nein neutrales Gesicht auf der linken Seite ' ...
                        'und ein wütendes Gesicht auf der rechten Seite sehen.\n' ...
                        'Ein Markierungspunkt wird zufällig auf einer Linie zwischen diesen Gesichtern platziert.\n' ...
                        'Sie haben 4 Sekunden Zeit, diesen Markierungspunkt zu bewegen. Je näher Sie ' ...
                        'den Punkt am wütenden Gesicht platzieren,\n' ...
                        'desto höher ist die Wahrscheinlichkeit, dass ein unangenehmes Bild ' ...
                        '(ein schreiendes Gesicht) erscheint.\n' ...
                        'Wenn kein unangenehmes Bild erscheint, sehen Sie einen leeren Bildschirm.' ...
                        '\n' ...
                        'Wenn Sie bereit sind, drücken Sie bitte die Leertaste, um mit der Aufgabe zu beginnen.'];
                    case 'en'
                        instrStr = ['In the following task, you will see a neutral face on the left side of each screen and an angry face ' ...
                        'on the right side.\n\n' ...
                        'A marker point will be randomly placed on a line between these faces.\n\n' ...
                        'You have 4 seconds to move this marker point. The closer you place the point to the angry face,\n\n' ...
                        'the higher the probability that an unpleasant image (a screaming face) will appear.\n\n' ...
                        'If no unpleasant image appears, you will see a blank screen.' ...
                        '\n\n' ...
                        'When you are ready, please press the spacebar to begin the task.'];
                end
                if instrIndex == 1
                    switch lang
                        case 'de'
                            instrStr = ['trialInstrDE'];
                        case 'en'
                            instrStr = ['trialInstrEN'];
                    end
                end
                DrawFormattedText(window, instrStr, 'center', 'center', white);
                Screen('Flip', window);
            else
                error('Input index "%d" is invalid', instrIndex);
            end
        end
    end
end