classdef instructionController
    properties
    end
    methods (Static)
        function displayInstruction(window, white, lang, instrIndex)
            if instrIndex == 0
                switch lang
                    case 'de'
                        instrStr = ['In der folgenden Aufgabe werden Sie auf jedem Bildschirm\nein neutrales Gesicht auf der linken Seite ' ...
                        'und ein wütendes Gesicht auf der rechten Seite sehen.\n' ...
                        'Ein Markierungspunkt wird zufällig auf einer Linie zwischen diesen Gesichtern platziert.\n' ...
                        'Sie haben 4 Sekunden Zeit, diesen Markierungspunkt zu bewegen. Je näher Sie ' ...
                        'den Punkt am wütenden Gesicht platzieren,\n' ...
                        'desto höher ist die Wahrscheinlichkeit, dass ein unangenehmes Bild ' ...
                        '(ein schreiendes Gesicht) erscheint.\n' ...
                        'Wenn kein unangenehmes Bild erscheint, sehen Sie einen leeren Bildschirm.' ...
                        '\n' ...
                        'Wenn Sie bereit sind, drücken Sie bitte die Leertaste, um mit der Aufgabe zu beginnen.'];
                    case 'en'
                        instrStr = ['In the following task, you will see a neutral face on the left side of each screen and an angry face ' ...
                        'on the right side.\n\n' ...
                        'A marker point will be randomly placed on a line between these faces.\n\n' ...
                        'You have 4 seconds to move this marker point. The closer you place the point to the angry face,\n\n' ...
                        'the higher the probability that an unpleasant image (a screaming face) will appear.\n\n' ...
                        'If no unpleasant image appears, you will see a blank screen.' ...
                        '\n\n' ...
                        'When you are ready, please press the spacebar to begin the task.'];
                end
            elseif instrIndex == 1
                switch lang
                    case 'de'
                        instrStr = ['Bei dieser Aufgabe haben Sie die Möglichkeit, Punkte zu sammeln.\n' ...
                        'In jedem Durchgang sehen Sie ein neutrales Gesicht auf der linken Seite und ein wütendes Gesicht ' ...
                        'auf der rechten Seite des Bildschirms.\n' ...
                        'Ein Marker erscheint zufällig positioniert auf einer Linie zwischen diesen Gesichtern.\n' ...
                        'Sie haben 4 Sekunden Zeit, um die Position dieses Markers mit den Steuerungselementen anzupassen.\n' ...
                        'Je näher Sie den Marker am wütenden Gesicht platzieren, desto höher ist die Wahrscheinlichkeit, ' ...
                        'ein unangenehmes Bild \n (ein schreiendes Gesicht) zu sehen.' ...
                        'Wenn das unangenehme Bild erscheint, erhalten Sie je nach aktueller Phase 2, 4 oder 6 Punkte.\n' ...
                        'Wenn kein unangenehmes Bild erscheint und stattdessen ein \n leerer Bildschirm angezeigt wird, ' ...
                        'werden für diesen Durchgang keine Punkte vergeben.\n' ... 
                        'Vor Beginn jeder Phase werden Sie darüber informiert, wie viele Punkte Sie gewinnen können.\n' ...
                        'Drücken Sie die Leertaste, wenn Sie bereit sind, zu beginnen.'];
                    case 'en'
                        instrStr = ['In this task, you will have the opportunity to earn points.\n\n' ...
                        'Each trial will display a neutral face on the left side and an angry face on the right side of your screen.\n\n' ...
                        'A marker will appear randomly positioned on a line between these faces.\n\n' ...
                        'You will have 4 seconds to adjust the marker position using the controls.\n\n' ...
                        'The closer you position the marker to the angry face, the higher the probability of seeing ' ...
                        'an unpleasant image (a screaming face).\n\n' ...
                        'If the unpleasant image appears, you will earn either 2, 4, or 6 points, depending on the current stage.\n\n' ...
                        'If no unpleasant image appears and you see a blank screen instead, no points will be awarded for that trial.\n\n' ...
                        'Before each stage begins, you will be informed about how many points you can win.\n\n' ...
                        '\n\n' ...
                        'Press the spacebar when you are ready to begin.'];
                end
            else
                error('Input index "%d" is invalid', instrIndex);
            end
            
            DrawFormattedText(window, instrStr, 'center', 'center', white);
            Screen('Flip', window);
        end

        function displayCompletion(window, white, grey, instrIndex)
            if instrIndex == 0
                WaitSecs(0.5)
                Screen('FillRect', window, grey);
                DrawFormattedText(window, 'Baseline phase complete!', 'center', 'center', white);
                Screen('Flip', window);
                WaitSecs(2);
            elseif instrIndex == 1
                WaitSecs(0.5)
                Screen('FillRect', window, grey);
                DrawFormattedText(window, 'Conflict phase complete!', 'center', 'center', white);
                Screen('Flip', window);
                WaitSecs(2);
            else
                WaitSecs(0.5)
                Screen('FillRect', window, grey);
                DrawFormattedText(window, 'Experiment finished. Closing the app...', 'center', 'center', white);
                Screen('Flip', window);
                WaitSecs(2);
            end
        end
    end
end